### ISSUE TITLE
AWI reference causes `isodoc` gem to crash

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#12]
```adoc

[bibliography]
== Normative References

* [[[ISO34000,ISO 34000]]], _Date and time -- Concepts and vocabulary_

[[terms]]
[source=ISO34000]
== Terms and Definitions
...

```

Error:

```sh
character content of element "from" invalid; must be a year @ 1644:40
character content of element "from" invalid; must be a year @ 1689:44
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
TypeError: no implicit conversion of nil into String
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/inline.rb:84:in `+'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/inline.rb:84:in `eref_parse'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/isodoc-1.0.1/lib/isodoc/function/to_word_html.rb:205:in `parse'
```

Line 1644 is exactly `<copyright>`. The value should not be `copyright value unknown`, just "unknown".

<img width="653" alt="Screen Shot 2019-09-04 at 4 14 08 PM" src="https://user-images.githubusercontent.com/11865/64237485-0709b500-cf2f-11e9-8214-75e7541f2c5d.png">

Moreover, we need to fix the `isodoc` gem to accept the `unknown` value here.

**Comment by andrew2net** [comment]
@ronaldtse as I understand, fixing `isodoc` isn't my job, is it?

**Comment by ronaldtse** [comment]
@andrew2net I'd like you to start having some experience with `isodoc`, I think @opoudjis will handle it for now, but he will need your help.
