### ISSUE TITLE
(URGENT) Crash with 0.5.0

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#17]
Crash with 0.5.0.

```
[relaton-iso] ("ISO/IEC 8824-1") found ISO/IEC 8824-1:2015
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/bin/metanorma)
ArgumentError: expected :on or :from argument
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/bibliographic_date.rb:28:in `initialize'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:173:in `new'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:173:in `block in fetch_dates'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:171:in `map'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:171:in `fetch_dates'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:28:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.5.0/lib/relaton_iso_bib/xml_parser.rb:22:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:302:in `block in fetch_relations'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.7/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:291:in `map'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:291:in `fetch_relations'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.5.0/lib/relaton_bib/xml_parser.rb:38:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.5.0/lib/relaton_iso_bib/xml_parser.rb:22:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.5.0/lib/relaton_iso_bib/xml_parser.rb:13:in `from_xml'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-0.8.1/lib/relaton_iso/processor.rb:25:in `from_xml'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.7.0/lib/relaton/db.rb:137:in `bib_retval'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.7.0/lib/relaton/db.rb:169:in `check_bibliocache'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.7.0/lib/relaton/db.rb:31:in `fetch'
```

An older version of the gems had the same problem:

```
fetching ISO 4217...
fetching ISO 7372...
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/bin/metanorma)
ArgumentError: expected :on or :from argument
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/bibliographic_date.rb:28:in `initialize'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:168:in `new'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:168:in `block in fetch_dates'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:166:in `map'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:166:in `fetch_dates'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:28:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.3.12/lib/relaton_iso_bib/xml_parser.rb:22:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:297:in `block in fetch_relations'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.5/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:286:in `map'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:286:in `fetch_relations'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-0.3.12/lib/relaton_bib/xml_parser.rb:38:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.3.12/lib/relaton_iso_bib/xml_parser.rb:22:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.3.12/lib/relaton_iso_bib/xml_parser.rb:13:in `from_xml'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-0.6.9/lib/relaton_iso/processor.rb:25:in `from_xml'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.14/lib/relaton/db.rb:138:in `bib_retval'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.14/lib/relaton/db.rb:169:in `check_bibliocache'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.14/lib/relaton/db.rb:32:in `fetch'
```

**Comment by ronaldtse** [comment]
Cleared cache, still crashed

**Comment by ronaldtse** [comment]
@andrew2net please add this to spec

**Comment by ronaldtse** [comment]
Seems that this particular document can reproduce it every time.

**Comment by andrew2net** [comment]
Fixed. You need to update `relaton-bib` and `relaton-iso` gems.

**Comment by ronaldtse** [comment]
Thanks @andrew2net , confirm fixed, but can you please add a spec for this case?

**Comment by ronaldtse** [comment]
Thanks @andrew2net !
