### ISSUE TITLE
(URGENT) Relaton-bib crashing creation of index with given non-MN XML files

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-bib#27]
In mn-samples-iso, it generates all output formats including STS XML.

Relaton MUST check whether a file can be parsed and should NOT crash in any case

```
$ make
...
echo "Running locally via bundle ..."; bundle exec relaton concatenate \
	  -t "ISO sample documents in Metanorma (Metanorma AsciiDoc syntax)" \
		-g "Metanorma : Standards for standards" \
		documents documents.rxl
Running locally via bundle ...
bundler: failed to load command: relaton (/Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/relaton)
NoMethodError: undefined method `text' for nil:NilClass
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-1.2.1/lib/relaton_bib/xml_parser.rb:417:in `block in fetch_ics'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:238:in `block in each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `upto'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-1.2.1/lib/relaton_bib/xml_parser.rb:416:in `map'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-1.2.1/lib/relaton_bib/xml_parser.rb:416:in `fetch_ics'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-1.2.1/lib/relaton_bib/xml_parser.rb:55:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-1.2.0/lib/relaton_iso_bib/xml_parser.rb:12:in `item_data'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-1.2.1/lib/relaton_bib/xml_parser.rb:11:in `from_xml'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-1.2.0/lib/relaton_iso/processor.rb:25:in `from_xml'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-cli-1.2.0/lib/relaton/cli.rb:38:in `parse_xml'
...
```

**Comment by ronaldtse** [comment]
It's dying here:

  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-bib-1.2.1/lib/relaton_bib/xml_parser.rb:417:in `block in fetch_ics'

```
      def fetch_ics(ext)
        return [] unless ext

        ext.xpath("ics").map do |ics|
          ICS.new code: ics.at("code").text, text: ics.at("text").text
        end
      end
```

On this file `documents/amendment/rice-amd.fdamd.rxl`:

At this location:

```
<ext>
<doctype>amendment</doctype>
...
<ics>
<code>67.060</code>
</ics>
...
```
