### ISSUE TITLE
relaton-bib-1.7.1/lib/relaton_bib/document_relation.rb:66:in `block in to_xml': undefined method `to_xml' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib#39]
Command `metanorma -x xml sources/00-027/document.adoc` for https://github.com/metanorma/mn-samples-ogc/blob/master/sources/00-027/document.adoc

<details><summary>Full stacktrace</summary>
<p>

```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/document_relation.rb:66:in `block in to_xml': undefined method `to_xml' for nil:NilClass (NoMethodError)
Did you mean?  to_yaml
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/document_relation.rb:64:in `to_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/bibliographic_item.rb:703:in `block (2 levels) in render_xml'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /__enclose_io_memfs__/lib/ruby/2.4.0/forwardable.rb:229:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/bibliographic_item.rb:703:in `block in render_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/bibliographic_item.rb:676:in `render_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/bibliographic_item.rb:313:in `block in to_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/bibliographic_item.rb:312:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-bib-1.7.1/lib/relaton_bib/bibliographic_item.rb:312:in `to_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/relaton-iso-bib-1.7.0/lib/relaton_iso_bib/iso_bibliographic_item.rb:158:in `to_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:96:in `smart_render_xml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:71:in `fetch_ref'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref.rb:73:in `isorefmatches'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref.rb:235:in `reference1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:14:in `block (2 levels) in reference'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:14:in `each'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:14:in `block in reference'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/utils.rb:128:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:13:in `reference'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/lists.rb:38:in `ulist'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/utils.rb:107:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/list.rb:30:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:26:in `block in bibliography_parse'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/ref_sect.rb:23:in `bibliography_parse'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/section.rb:83:in `block in section'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/utils.rb:128:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/section.rb:68:in `section'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/utils.rb:107:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/base.rb:184:in `block in middle'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/base.rb:183:in `middle'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/base.rb:155:in `block in makexml1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/utils.rb:128:in `noko'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/base.rb:155:in `makexml1'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/base.rb:161:in `makexml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-ogc-1.2.9/lib/asciidoctor/ogc/converter.rb:24:in `makexml'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/base.rb:136:in `document'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-standoc-1.6.5/lib/asciidoctor/standoc/utils.rb:107:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/input/asciidoc.rb:24:in `process'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/compile.rb:122:in `process_input'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-1.2.2/lib/metanorma/compile.rb:21:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.0/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.0/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.0/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.0/lib/metanorma/cli/command.rb:42:in `compile'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-cli-1.4.0/lib/metanorma/cli.rb:62:in `start'
	from /__enclose_io_memfs__/local/metanorma:190:in `<main>'
```

</p>
</details>

**Comment by andrew2net** [comment]
@CAMOBAP I don't get this error:

<details>
  <summary>Full stacktrace</summary>

```
mn-samples-ogc git:(master) metanorma -x xml sources/00-027/document.adoc
Style: Abstract is missing!
Style: Keywords are missing!
Style: Preface is missing!
Style: Submitters is missing!
Metanorma XML Style Warning: (XML Line 000111): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000141): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000151): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000154): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000179): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000179): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000271): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000301): Hanging paragraph in clause
Metanorma XML Syntax: (XML Line 000009:6): character content of element "on" invalid; must be a string matching the regular expression "([\+\-]?\d{4})((-?)((0[1-9]|1[0-2])((-?)([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6]))))?"
Metanorma XML Syntax: (XML Line 000180:75): element "clause" not allowed here; expected element "abstract" or "foreword"
Metanorma XML Syntax: (XML Line 000186:98): element "clause" not allowed here; expected element "abstract" or "foreword"
Metanorma XML Syntax: (XML Line 000202:111): element "clause" not allowed here; expected element "abstract" or "foreword"
Metanorma XML Syntax: (XML Line 000205:102): element "clause" not allowed here; expected element "abstract" or "foreword"
Metanorma XML Syntax: (XML Line 000205:269): element "preface" incomplete; missing required element "foreword"
Metanorma XML Syntax: (XML Line 000539:16): element "ogc-standard" incomplete; missing required element "bibliography"
mn-samples-ogc git:(master)
```
</details>

**Comment by CAMOBAP** [comment]
@andrew2net it reproduces on ruby 2.4.0 (with nokogiri-1.10.10), can you confirm that you still cannot reproduce it?

**Comment by andrew2net** [comment]
@CAMOBAP eventually I reproduce this error but with `metanorma -x xml repos/ogc-tcpnp/sources/ogc-tcpnp.adoc` command.

**Comment by andrew2net** [comment]
This error is fixed in the `relaton` gem. Please use relaton v 1.7.2

**Comment by ronaldtse** [comment]
Thank you guys!
