### ISSUE TITLE
lib/relaton_bib/hash_converter.rb:440:in `block in symbolize': undefined method `to_sym' for 404:Integer

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib#44]
- https://github.com/metanorma/mn-samples-itu/runs/2191822282?check_suite_focus=true#step:7:1506

can be reproduced with `metanorma site generate . -o published -c metanorma.yml --agree-to-terms` with docs in https://github.com/metanorma/mn-samples-itu repository

<details><summary>Stack trace</summary>
<p>

```ruby

/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:440:in `block in symbolize': undefined method `to_sym' for 404:Integer (NoMethodError)
Did you mean?  to_s
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:439:in `each'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:439:in `reduce'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:439:in `symbolize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-bib-1.7.4/lib/relaton_bib/hash_converter.rb:12:in `hash_to_bib'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-itu-1.7.5/lib/relaton_itu/hit_collection.rb:31:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:22:in `new'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:22:in `search'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:84:in `search_filter'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:124:in `itubib_get1'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-itu-1.7.5/lib/relaton_itu/itu_bibliography.rb:43:in `get'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-itu-1.7.5/lib/relaton_itu/processor.rb:17:in `get'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-1.7.6/lib/relaton/db.rb:380:in `net_retry'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-1.7.6/lib/relaton/db.rb:366:in `new_bib_entry'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-1.7.6/lib/relaton/db.rb:348:in `check_bibliocache'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/relaton-1.7.6/lib/relaton/db.rb:60:in `fetch'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:69:in `fetch_ref'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref.rb:191:in `refitem1'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref.rb:183:in `refitem'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref.rb:234:in `reference1'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:14:in `block (2 levels) in reference'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:14:in `each'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:14:in `block in reference'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:13:in `reference'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/lists.rb:38:in `ulist'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/list.rb:30:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:26:in `block in bibliography_parse'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/ref_sect.rb:23:in `bibliography_parse'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/section.rb:77:in `block in section'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/section.rb:62:in `section'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:75:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `block in content'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `map'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/abstract_block.rb:84:in `content'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:1005:in `content'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:190:in `block in middle'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:394:in `insert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:377:in `method_missing'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:189:in `middle'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:161:in `block in makexml1'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:295:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `new'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/builder.rb:254:in `with'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:35:in `noko'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:161:in `makexml1'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:167:in `makexml'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-itu-1.2.15/lib/asciidoctor/itu/converter.rb:38:in `makexml'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/base.rb:142:in `document'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.8.6/lib/asciidoctor/standoc/utils.rb:14:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb:936:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.12/lib/asciidoctor/convert.rb:119:in `convert'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.2.7/lib/metanorma/input/asciidoc.rb:24:in `process'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.2.7/lib/metanorma/processor.rb:24:in `input_to_isodoc'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.2.7/lib/metanorma/compile.rb:137:in `process_input'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-1.2.7/lib/metanorma/compile.rb:24:in `compile'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:81:in `compile'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `block in generate'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `each'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:28:in `generate'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/site_generator.rb:23:in `generate'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli/commands/site.rb:25:in `generate'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/lib/metanorma/cli.rb:67:in `start'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/metanorma-cli-1.4.6/exe/metanorma:20:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/metanorma:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/bin/metanorma:23:in `<main>'
```

</p>
</details>

**Comment by andrew2net** [comment]
@CAMOBAP I don't get this error on my comp. Did you try running this command on your local comp?

**Comment by CAMOBAP** [comment]
@andrew2net you are right, probably something wrong with gem resolving, I have tried on both 2.4 and 2.6 works in both cases
