### ISSUE TITLE
Fatal Error: missing keyword: :content

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib#71]
https://github.com/metanorma/metanorma-docker-private/actions/runs/4403988213/jobs/7714370776

```
Fatal Error: missing keyword: :content
/usr/local/bundle/gems/relaton-bib-1.14.6/lib/relaton_bib/formatted_string.rb:19:in `initialize': missing keyword: :content (ArgumentError)
	from /usr/local/bundle/gems/relaton-bib-1.14.6/lib/relaton_bib/bibliographic_item.rb:229:in `new'
	from /usr/local/bundle/gems/relaton-bib-1.14.6/lib/relaton_bib/bibliographic_item.rb:229:in `block in initialize'
	from /usr/local/bundle/gems/relaton-bib-1.14.6/lib/relaton_bib/bibliographic_item.rb:228:in `map'
	from /usr/local/bundle/gems/relaton-bib-1.14.6/lib/relaton_bib/bibliographic_item.rb:228:in `initialize'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/merge_bibitems.rb:28:in `new'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/merge_bibitems.rb:28:in `to_noko'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/cleanup_ref.rb:29:in `merge_bibitem_from_formattedref_spans'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/cleanup_ref.rb:12:in `block in formattedref_spans'
	from /usr/local/bundle/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /usr/local/bundle/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /usr/local/bundle/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/cleanup_ref.rb:10:in `formattedref_spans'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/cleanup_ref.rb:243:in `bibitem_cleanup'
	from /usr/local/bundle/gems/metanorma-iso-2.4.0/lib/metanorma/iso/cleanup.rb:137:in `bibitem_cleanup'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/cleanup.rb:45:in `cleanup'
	from /usr/local/bundle/gems/metanorma-bsi-1.0.0/lib/metanorma/bsi/cleanup.rb:7:in `cleanup'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/base.rb:197:in `makexml'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/base.rb:148:in `document1'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/base.rb:137:in `document'
	from /usr/local/bundle/gems/metanorma-standoc-2.4.0/lib/metanorma/standoc/utils.rb:13:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:956:in `convert'
	from /usr/local/bundle/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:120:in `convert'
	from /usr/local/bundle/gems/metanorma-1.5.7/lib/metanorma/input/asciidoc.rb:18:in `process'
	from /usr/local/bundle/gems/metanorma-1.5.7/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from /usr/local/bundle/gems/metanorma-1.5.7/lib/metanorma/compile.rb:60:in `process_input_adoc'
	from /usr/local/bundle/gems/metanorma-1.5.7/lib/metanorma/compile.rb:42:in `process_input'
	from /usr/local/bundle/gems/metanorma-1.5.7/lib/metanorma/compile.rb:33:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/site_generator.rb:91:in `compile'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/site_generator.rb:31:in `block in generate'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/site_generator.rb:31:in `each'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/site_generator.rb:31:in `generate'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/lib/metanorma/cli.rb:34:in `start'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/exe/metanorma:25:in `block in <top (required)>'
	from /usr/local/bundle/gems/metanorma-cli-1.6.15.pre.pre/exe/metanorma:43:in `<top (required)>'
	from /usr/local/bundle/bin/metanorma:25:in `load'
	from /usr/local/bundle/bin/metanorma:25:in `<main>'
```

**Comment by andrew2net** [comment]
fixed in v 1.14.7
