### ISSUE TITLE
`get_org': undefined method `xpath' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib#72]
https://github.com/metanorma/metanorma-cli/actions/runs/4542218735/jobs/8006345798#step:10:1511

```
/opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:369:in `get_org': undefined method `xpath' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:398:in `block in get_person'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:392:in `map'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:392:in `get_person'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:508:in `block in fetch_contributors'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:506:in `map'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:506:in `fetch_contributors'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:46:in `item_data'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:18:in `from_xml'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli.rb:64:in `parse_xml'
...
```

<details><summary>Full stack trace</summary>
<p>

```
/opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:369:in `get_org': undefined method `xpath' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:398:in `block in get_person'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:392:in `map'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:392:in `get_person'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:508:in `block in fetch_contributors'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `block in each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `upto'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.13.10-x86_64-linux/lib/nokogiri/xml/node_set.rb:233:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:506:in `map'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:506:in `fetch_contributors'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:46:in `item_data'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.7/lib/relaton_bib/xml_parser.rb:18:in `from_xml'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli.rb:64:in `parse_xml'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/bibdata.rb:41:in `from_xml'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:196:in `bibdata_instance'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:150:in `block in concatenate_files'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:142:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:142:in `reduce'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:142:in `concatenate_files'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:86:in `bibcollection'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:157:in `concatenate_and_write_to_files'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.0/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
	from /home/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:71:in `build_collection_file'
	from /home/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:34:in `block in generate'
	from /home/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:33:in `chdir'
	from /home/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:33:in `generate'
	from /home/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /home/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /home/runner/work/metanorma-cli/metanorma-cli/lib/metanorma/cli.rb:34:in `start'
	from /home/runner/work/metanorma-cli/metanorma-cli/exe/metanorma:25:in `block in <top (required)>'
	from /home/runner/work/metanorma-cli/metanorma-cli/exe/metanorma:43:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/bin/metanorma:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/cli.rb:492:in `exec'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/exe/bundle:45:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/bundler-2.4.10/exe/bundle:33:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/bin/bundle:23:in `<main>'
```

</p>
</details>

**Comment by andrew2net** [comment]
@CAMOBAP fixed in v 1.14.8
