### ISSUE TITLE
undefined method `to_xml' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib#74]
```stacktrace
/Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/contributor.rb:150:in `block in to_xml': undefined method `to_xml' for nil:NilClass (NoMethodError)
Did you mean?  to_yaml
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/contributor.rb:145:in `to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/person.rb:94:in `block (2 levels) in to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/person.rb:94:in `each'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/person.rb:94:in `block in to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/person.rb:92:in `to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/contribution_info.rb:96:in `to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:609:in `block (3 levels) in render_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:607:in `block (2 levels) in render_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:606:in `each'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:606:in `block in render_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:598:in `render_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:367:in `block in to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/nokogiri-1.14.2-x86_64-darwin/lib/nokogiri/xml/builder.rb:331:in `initialize'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:366:in `new'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-bib-1.14.10/lib/relaton_bib/bibliographic_item.rb:366:in `to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.2/lib/relaton/bibdata.rb:49:in `to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.2/lib/relaton/bibcollection.rb:72:in `block in to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.2/lib/relaton/bibcollection.rb:70:in `each'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.2/lib/relaton/bibcollection.rb:70:in `to_xml'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.2/lib/relaton/cli/relaton_file.rb:157:in `concatenate_and_write_to_files'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.2/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
	from /Users/runner/hostedtoolcache/Ruby/2.7.8/x64/lib/ruby/gems/2.7.0/gems/relaton-cli-1.15.2/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
```

Full log https://github.com/metanorma/metanorma-cli/actions/runs/4654941171/jobs/8250443201#step:10:1513

**Comment by andrew2net** [comment]
The issue is caused by missing an organization attribute in the affiliation. So it was a problem with the source data. But it seems the problem has gone now. In the [log](https://github.com/metanorma/metanorma-cli/actions/runs/5049848646/jobs/9059827787) you can see that there isn't such an issue anymore. There are other tests that fail, but they are not related to relaton.
